In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=sns.load_dataset("titanic")
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [3]:
df.shape

(891, 15)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [5]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [6]:
x=df.describe()
x

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [7]:
df["age"].fillna(df["age"].mean(),inplace=True)
df

survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S   
1           1       1  female  38.000000      1      0  71.2833        C   
2           1       3  female  26.000000      0      0   7.9250        S   
3           1       1  female  35.000000      1      0  53.1000        S   
4           0       3    male  35.000000      0      0   8.0500        S   
..        ...     ...     ...        ...    ...    ...      ...      ...   
886         0       2    male  27.000000      0      0  13.0000        S   
887         1       1  female  19.000000      0      0  30.0000        S   
888         0       3  female  29.699118      1      2  23.4500        S   
889         1       1    male  26.000000      0      0  30.0000        C   
890         0       3    male  32.000000      0      0   7.7500        Q   

      class    who  adult_male deck  embark_town alive  alone  
0     Third    man        True  NaN  Southampton    no  False  
1     First  woman       False    C    Cherbourg   yes  False  
2     Third  woman       False  NaN  Southampton   yes   True  
3     First  woman       False    C  Southampton   yes  False  
4     Third    man        True  NaN  Southampton    no   True  
..      ...    ...         ...  ...          ...   ...    ...  
886  Second    man        True  NaN  Southampton    no   True  
887   First  woman       False    B  Southampton   yes   True  
888   Third  woman       False  NaN  Southampton    no  False  
889   First    man        True    C    Cherbourg   yes   True  
890   Third    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [8]:
df["embarked"].fillna(df["embarked"].mode()[0],inplace=True)
df

survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S   
1           1       1  female  38.000000      1      0  71.2833        C   
2           1       3  female  26.000000      0      0   7.9250        S   
3           1       1  female  35.000000      1      0  53.1000        S   
4           0       3    male  35.000000      0      0   8.0500        S   
..        ...     ...     ...        ...    ...    ...      ...      ...   
886         0       2    male  27.000000      0      0  13.0000        S   
887         1       1  female  19.000000      0      0  30.0000        S   
888         0       3  female  29.699118      1      2  23.4500        S   
889         1       1    male  26.000000      0      0  30.0000        C   
890         0       3    male  32.000000      0      0   7.7500        Q   

      class    who  adult_male deck  embark_town alive  alone  
0     Third    man        True  NaN  Southampton    no  False  
1     First  woman       False    C    Cherbourg   yes  False  
2     Third  woman       False  NaN  Southampton   yes   True  
3     First  woman       False    C  Southampton   yes  False  
4     Third    man        True  NaN  Southampton    no   True  
..      ...    ...         ...  ...          ...   ...    ...  
886  Second    man        True  NaN  Southampton    no   True  
887   First  woman       False    B  Southampton   yes   True  
888   Third  woman       False  NaN  Southampton    no  False  
889   First    man        True    C    Cherbourg   yes   True  
890   Third    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [9]:
df["embark_town"].fillna(df["embark_town"].mode()[0],inplace=True)
df

survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S   
1           1       1  female  38.000000      1      0  71.2833        C   
2           1       3  female  26.000000      0      0   7.9250        S   
3           1       1  female  35.000000      1      0  53.1000        S   
4           0       3    male  35.000000      0      0   8.0500        S   
..        ...     ...     ...        ...    ...    ...      ...      ...   
886         0       2    male  27.000000      0      0  13.0000        S   
887         1       1  female  19.000000      0      0  30.0000        S   
888         0       3  female  29.699118      1      2  23.4500        S   
889         1       1    male  26.000000      0      0  30.0000        C   
890         0       3    male  32.000000      0      0   7.7500        Q   

      class    who  adult_male deck  embark_town alive  alone  
0     Third    man        True  NaN  Southampton    no  False  
1     First  woman       False    C    Cherbourg   yes  False  
2     Third  woman       False  NaN  Southampton   yes   True  
3     First  woman       False    C  Southampton   yes  False  
4     Third    man        True  NaN  Southampton    no   True  
..      ...    ...         ...  ...          ...   ...    ...  
886  Second    man        True  NaN  Southampton    no   True  
887   First  woman       False    B  Southampton   yes   True  
888   Third  woman       False  NaN  Southampton    no  False  
889   First    man        True    C    Cherbourg   yes   True  
890   Third    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [10]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [11]:
df=df.drop("deck",axis=1)
df=df.drop("embark_town",axis=1)
df=df.drop("who",axis=1)

In [12]:
x=df.iloc[:,0:11]
x

survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S   
1           1       1  female  38.000000      1      0  71.2833        C   
2           1       3  female  26.000000      0      0   7.9250        S   
3           1       1  female  35.000000      1      0  53.1000        S   
4           0       3    male  35.000000      0      0   8.0500        S   
..        ...     ...     ...        ...    ...    ...      ...      ...   
886         0       2    male  27.000000      0      0  13.0000        S   
887         1       1  female  19.000000      0      0  30.0000        S   
888         0       3  female  29.699118      1      2  23.4500        S   
889         1       1    male  26.000000      0      0  30.0000        C   
890         0       3    male  32.000000      0      0   7.7500        Q   

      class  adult_male alive  
0     Third        True    no  
1     First       False   yes  
2     Third       False   yes  
3     First       False   yes  
4     Third        True    no  
..      ...         ...   ...  
886  Second        True    no  
887   First       False   yes  
888   Third       False    no  
889   First        True   yes  
890   Third        True    no  

[891 rows x 11 columns]

In [13]:
y=df.iloc[:,-1:]
y

alone
0    False
1    False
2     True
3    False
4     True
..     ...
886   True
887   True
888  False
889   True
890   True

[891 rows x 1 columns]

In [14]:
x.shape

(891, 11)

In [15]:
df["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [16]:
df["embarked"].value_counts()

S    646
C    168
Q     77
Name: embarked, dtype: int64

In [17]:
df["class"].value_counts()

Third     491
First     216
Second    184
Name: class, dtype: int64

In [18]:
df["adult_male"].value_counts()

True     537
False    354
Name: adult_male, dtype: int64

In [19]:
df["alive"].value_counts()

no     549
yes    342
Name: alive, dtype: int64

In [20]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_transformer

In [21]:
le=LabelEncoder()
df["sex"]=le.fit_transform(df["sex"])
df["embarked"]=le.fit_transform(df["embarked"])
df["class"]=le.fit_transform(df["class"])
df["adult_male"]=le.fit_transform(df["adult_male"])
df["alive"]=le.fit_transform(df["alive"])
df["alone"]=le.fit_transform(df["alone"])

In [22]:
df

survived  pclass  sex        age  sibsp  parch     fare  embarked  class  \
0           0       3    1  22.000000      1      0   7.2500         2      2   
1           1       1    0  38.000000      1      0  71.2833         0      0   
2           1       3    0  26.000000      0      0   7.9250         2      2   
3           1       1    0  35.000000      1      0  53.1000         2      0   
4           0       3    1  35.000000      0      0   8.0500         2      2   
..        ...     ...  ...        ...    ...    ...      ...       ...    ...   
886         0       2    1  27.000000      0      0  13.0000         2      1   
887         1       1    0  19.000000      0      0  30.0000         2      0   
888         0       3    0  29.699118      1      2  23.4500         2      2   
889         1       1    1  26.000000      0      0  30.0000         0      0   
890         0       3    1  32.000000      0      0   7.7500         1      2   

     adult_male  alive  alone  
0             1      0      0  
1             0      1      0  
2             0      1      1  
3             0      1      0  
4             1      0      1  
..          ...    ...    ...  
886           1      0      1  
887           0      1      1  
888           0      0      0  
889           1      1      1  
890           1      0      1  

[891 rows x 12 columns]

In [23]:
df["sex"].unique()

array([1, 0])

In [24]:
df.shape

(891, 12)

In [25]:
sc=StandardScaler()
df=sc.fit_transform(df)

In [26]:
df

array([[-0.78927234,  0.82737724,  0.73769513, ...,  0.81192233,
        -0.78927234, -1.2316449 ],
       [ 1.2669898 , -1.56610693, -1.35557354, ..., -1.2316449 ,
         1.2669898 , -1.2316449 ],
       [ 1.2669898 ,  0.82737724, -1.35557354, ..., -1.2316449 ,
         1.2669898 ,  0.81192233],
       ...,
       [-0.78927234,  0.82737724, -1.35557354, ..., -1.2316449 ,
        -0.78927234, -1.2316449 ],
       [ 1.2669898 , -1.56610693,  0.73769513, ...,  0.81192233,
         1.2669898 ,  0.81192233],
       [-0.78927234,  0.82737724,  0.73769513, ...,  0.81192233,
        -0.78927234,  0.81192233]])

In [27]:
df.shape

(891, 12)

In [28]:
x=df[:,0:11]
x

array([[-0.78927234,  0.82737724,  0.73769513, ...,  0.82737724,
         0.81192233, -0.78927234],
       [ 1.2669898 , -1.56610693, -1.35557354, ..., -1.56610693,
        -1.2316449 ,  1.2669898 ],
       [ 1.2669898 ,  0.82737724, -1.35557354, ...,  0.82737724,
        -1.2316449 ,  1.2669898 ],
       ...,
       [-0.78927234,  0.82737724, -1.35557354, ...,  0.82737724,
        -1.2316449 , -0.78927234],
       [ 1.2669898 , -1.56610693,  0.73769513, ..., -1.56610693,
         0.81192233,  1.2669898 ],
       [-0.78927234,  0.82737724,  0.73769513, ...,  0.82737724,
         0.81192233, -0.78927234]])

In [29]:
x=pd.DataFrame(x)
x

0         1         2         3         4         5         6  \
0   -0.789272  0.827377  0.737695 -0.592481  0.432793 -0.473674 -0.502445   
1    1.266990 -1.566107 -1.355574  0.638789  0.432793 -0.473674  0.786845   
2    1.266990  0.827377 -1.355574 -0.284663 -0.474545 -0.473674 -0.488854   
3    1.266990 -1.566107 -1.355574  0.407926  0.432793 -0.473674  0.420730   
4   -0.789272  0.827377  0.737695  0.407926 -0.474545 -0.473674 -0.486337   
..        ...       ...       ...       ...       ...       ...       ...   
886 -0.789272 -0.369365  0.737695 -0.207709 -0.474545 -0.473674 -0.386671   
887  1.266990 -1.566107 -1.355574 -0.823344 -0.474545 -0.473674 -0.044381   
888 -0.789272  0.827377 -1.355574  0.000000  0.432793  2.008933 -0.176263   
889  1.266990 -1.566107  0.737695 -0.284663 -0.474545 -0.473674 -0.044381   
890 -0.789272  0.827377  0.737695  0.177063 -0.474545 -0.473674 -0.492378   

            7         8         9        10  
0    0.585954  0.827377  0.811922 -0.789272  
1   -1.942303 -1.566107 -1.231645  1.266990  
2    0.585954  0.827377 -1.231645  1.266990  
3    0.585954 -1.566107 -1.231645  1.266990  
4    0.585954  0.827377  0.811922 -0.789272  
..        ...       ...       ...       ...  
886  0.585954 -0.369365  0.811922 -0.789272  
887  0.585954 -1.566107 -1.231645  1.266990  
888  0.585954  0.827377 -1.231645 -0.789272  
889 -1.942303 -1.566107  0.811922  1.266990  
890 -0.678175  0.827377  0.811922 -0.789272  

[891 rows x 11 columns]

In [31]:
y=df[:,-1:]
y

array([[-1.2316449 ],
       [-1.2316449 ],
       [ 0.81192233],
       [-1.2316449 ],
       [ 0.81192233],
       [ 0.81192233],
       [ 0.81192233],
       [-1.2316449 ],
       [-1.2316449 ],
       [-1.2316449 ],
       [-1.2316449 ],
       [ 0.81192233],
       [ 0.81192233],
       [-1.2316449 ],
       [ 0.81192233],
       [ 0.81192233],
       [-1.2316449 ],
       [ 0.81192233],
       [-1.2316449 ],
       [ 0.81192233],
       [ 0.81192233],
       [ 0.81192233],
       [ 0.81192233],
       [ 0.81192233],
       [-1.2316449 ],
       [-1.2316449 ],
       [ 0.81192233],
       [-1.2316449 ],
       [ 0.81192233],
       [ 0.81192233],
       [ 0.81192233],
       [-1.2316449 ],
       [ 0.81192233],
       [ 0.81192233],
       [-1.2316449 ],
       [-1.2316449 ],
       [ 0.81192233],
       [ 0.81192233],
       [-1.2316449 ],
       [-1.2316449 ],
       [-1.2316449 ],
       [-1.2316449 ],
       [ 0.81192233],
       [-1.2316449 ],
       [ 0.81192233],
       [ 0

In [32]:
y=pd.DataFrame(y)
y

0
0   -1.231645
1   -1.231645
2    0.811922
3   -1.231645
4    0.811922
..        ...
886  0.811922
887  0.811922
888 -1.231645
889  0.811922
890  0.811922

[891 rows x 1 columns]

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [36]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 11)
(179, 11)
(712, 1)
(179, 1)
